#FILES
- name: variables from files
  hosts: localhost
  vars_files:
    variables.yaml
  tasks: 
  - name: print variables from files
    ansible.builtin.debug:
       this {{hero}} acted {{movie}} releaesed in {{year}}


