- name: installing packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages in order
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - git
    - mysql
    - nginx
    - aaa